feat: line-height e spacing
animaliads/animalia-design-tokens pull request #7
Opened 2021-05-31 19:17 UTC by nicoleoliveira

Adiciona novos tokens para o line-height e spacing-squish

**Revisão:**
- verificar se o build é executado corretamente gerando os pacotes finais. `(npm run build)` conforme o Zeplin

2021-05-31 21:49 UTC, edioli requested changes
Conferi os novos tokens e a única observação é que faltou o token `line-height-auto`, pra quando se for adotar o padrão da fonte, assim como tem no letter spacing.
Os demais tokens estão certinho :)

2021-06-01 11:59 UTC, nicoleoliveira commented
> Conferi os novos tokens e a única observação é que faltou o token `line-height-auto`, pra quando se for adotar o padrão da fonte, assim como tem no letter spacing.
> Os demais tokens estão certinho :)

Corrigido :) Obrigada @edioli

2021-06-01 12:17 UTC, edioli submitted a review, later dismissed

2021-06-01 14:27 UTC, edioli approved these changes

2021-06-03 13:41 UTC, merged